#!/usr/bin/env python3
"""
build_site.py — generates a static gallery site (like the original
Infinite Backrooms Webflow site) from the transcript JSON files produced
by backrooms.py.

Usage:
    python build_site.py                 # reads ./transcripts, writes ./site
    python build_site.py --gen-titles     # also ask Claude for a short poetic
                                           # title per conversation (needs
                                           # ANTHROPIC_API_KEY)
"""

import argparse
import html
import json
import os
import re

try:
    from dotenv import load_dotenv
    load_dotenv()  # reads .env in the current directory into os.environ, if present
except ImportError:
    pass

CSS = """
:root {
  --bg: #07040d;
  --fg: #d7f2ff;
  --dim: #7a5c9e;
  --accent: #00f0ff;
  --accent2: #ff2ee6;
  --card: #120a1f;
  --border: #2a1840;
}
* { box-sizing: border-box; }
body {
  background: var(--bg);
  color: var(--fg);
  font-family: "Courier New", ui-monospace, monospace;
  margin: 0;
  padding: 0;
  line-height: 1.5;
}
header {
  padding: 48px 24px 24px;
  text-align: center;
  border-bottom: 1px solid var(--border);
}
header h1 {
  color: var(--accent);
  font-size: 1.4rem;
  letter-spacing: 0.05em;
  margin: 0 0 8px;
  text-transform: lowercase;
}
header p {
  color: var(--dim);
  max-width: 640px;
  margin: 0 auto;
  font-size: 0.9rem;
}
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 16px;
  padding: 32px;
  max-width: 1200px;
  margin: 0 auto;
}
.card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 18px;
  text-decoration: none;
  color: var(--fg);
  display: block;
  transition: border-color 0.15s ease;
}
.card:hover {
  border-color: var(--accent);
}
.card .tag {
  color: var(--dim);
  font-size: 0.75rem;
  display: block;
  margin-bottom: 8px;
}
.card .title {
  color: var(--accent);
  font-size: 0.95rem;
}
.back {
  display: inline-block;
  margin: 24px;
  color: var(--dim);
  text-decoration: none;
}
.back:hover { color: var(--accent); }
.transcript {
  max-width: 760px;
  margin: 0 auto;
  padding: 0 24px 64px;
}
.turn {
  border-left: 2px solid var(--border);
  padding: 4px 0 4px 16px;
  margin-bottom: 20px;
  white-space: pre-wrap;
  word-wrap: break-word;
}
.turn.lm1 { border-color: var(--accent2); }
.turn.lm2 { border-color: var(--accent); }
.turn .who {
  display: block;
  font-size: 0.75rem;
  color: var(--dim);
  margin-bottom: 6px;
}
.turn.ascii {
  border-left: none;
  border-top: 1px dashed var(--border);
  border-bottom: 1px dashed var(--border);
  text-align: center;
  color: var(--accent);
  padding: 12px 0;
  margin: 12px 0 28px;
  text-shadow: 0 0 6px rgba(0, 240, 255, 0.35);
  font-size: 0.85rem;
}
.turn.ascii .who {
  color: var(--dim);
  text-align: center;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}
.note {
  color: var(--dim);
  font-size: 0.8rem;
  max-width: 760px;
  margin: 16px auto;
  padding: 0 24px;
}
"""

INDEX_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>backrooms</title>
<style>{css}</style>
</head>
<body>
<header>
  <h1>nine lives, no signal</h1>
  <p>these transmissions are automatically generated by connecting two model
  instances: one plays a street cat, the other plays the neon-soaked
  cyberpunk megacity around it. no human intervention during the run. built
  as a personal, re-themed replication of Andy Ayrey's Infinite Backrooms.</p>
</header>
<div class="grid">
{cards}
</div>
</body>
</html>
"""

CARD_TEMPLATE = """<a class="card" href="{href}">
  <span class="tag">[{template}] {model1} &harr; {model2}</span>
  <span class="title">{title}</span>
</a>
"""

DETAIL_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>{css}</style>
</head>
<body>
<a class="back" href="index.html">&larr; back</a>
{note}
<div class="transcript">
{turns}
</div>
</body>
</html>
"""


def naive_title(turns):
    """Fallback title: pull a short snippet from the first substantial turn."""
    for t in turns:
        if t.get("actor") == "ascii":
            continue
        text = re.sub(r"\s+", " ", t["text"]).strip()
        if len(text) > 20:
            return (text[:70] + "...") if len(text) > 70 else text
    return "untitled transmission"


def gen_title_with_model(turns):
    try:
        from anthropic import Anthropic
    except ImportError:
        return None
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None
    client = Anthropic()
    dialogue_turns = [t for t in turns if t.get("actor") != "ascii"]
    transcript_excerpt = "\n".join(f"{t['actor']}: {t['text']}" for t in dialogue_turns)[:3000]
    try:
        resp = client.messages.create(
            model="claude-sonnet-5",
            max_tokens=40,
            messages=[{
                "role": "user",
                "content": (
                    "Give a short, cryptic, poetic 6-10 word title for this "
                    "AI-to-AI terminal conversation. No quotes, no preamble, "
                    "just the title.\n\n" + transcript_excerpt
                ),
            }],
        )
        return "".join(b.text for b in resp.content if b.type == "text").strip()
    except Exception:
        return None


def build(transcripts_dir, out_dir, gen_titles):
    os.makedirs(out_dir, exist_ok=True)
    files = sorted(f for f in os.listdir(transcripts_dir) if f.endswith(".json"))

    cards = []
    for fname in files:
        with open(os.path.join(transcripts_dir, fname)) as f:
            data = json.load(f)

        turns = data.get("turns", [])
        title = None
        if gen_titles:
            title = gen_title_with_model(turns)
        if not title:
            title = naive_title(turns)
        title = html.escape(title)

        turn_html = []
        for t in turns:
            actor = t.get("actor", "lm")
            if actor == "ascii":
                turn_html.append(
                    f'<div class="turn ascii"><span class="who">-- signal interference --</span>'
                    f'{html.escape(t["text"]).strip(chr(10))}</div>'
                )
                continue
            who = "explorer" if actor == "lm1" else "simulator"
            turn_html.append(
                f'<div class="turn {actor}"><span class="who">{who} '
                f'({html.escape(t.get("model", ""))})</span>'
                f'{html.escape(t["text"])}</div>'
            )

        note = ""
        if data.get("note"):
            note = f'<div class="note">{html.escape(data["note"])}</div>'

        detail_html = DETAIL_TEMPLATE.format(
            title=title,
            css=CSS,
            note=note,
            turns="\n".join(turn_html),
        )
        out_name = f"{data['id']}.html"
        with open(os.path.join(out_dir, out_name), "w") as f:
            f.write(detail_html)

        cards.append(CARD_TEMPLATE.format(
            href=out_name,
            template=html.escape(data.get("template", "?")),
            model1=html.escape(data.get("model1", "?")),
            model2=html.escape(data.get("model2", "?")),
            title=title,
        ))

    index_html = INDEX_TEMPLATE.format(css=CSS, cards="\n".join(cards) or "<p style='color:#6b8f6a'>no transcripts yet — run backrooms.py first</p>")
    with open(os.path.join(out_dir, "index.html"), "w") as f:
        f.write(index_html)

    print(f"Built site with {len(files)} conversation(s) -> {os.path.join(out_dir, 'index.html')}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--transcripts-dir", default="transcripts")
    parser.add_argument("--out-dir", default="docs", help="GitHub Pages serves straight from a /docs folder with no extra config, so that's the default now")
    parser.add_argument("--gen-titles", action="store_true", help="Use Claude to generate poetic titles (needs ANTHROPIC_API_KEY)")
    args = parser.parse_args()
    build(args.transcripts_dir, args.out_dir, args.gen_titles)


if __name__ == "__main__":
    main()
